### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [sergot/openssl#101]
Can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?

I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by AntonOks** [comment]
@sergot @dwarring @ugexe @usev6 @patrickbkr - could someone, please

**Comment by sergot** [comment]
I will into tomorrow, and into other modules as well ;)

**Comment by sergot** [comment]
@AntonOks done, thanks again!
