### ISSUE TITLE
Failure to install on Windows 10

### ISSUE THREAD

**Issue by Odud** [sergot/openssl#19]
I was installing IO::Socket::SSL on Windows 10 using perl6 version 2016.01.1 and received the following error from the install of OpenSLL. I've no idea what this error means or how to work around it.

PS C:\Users\langb> panda install IO::Socket::SSL;
==> IO::Socket::SSL depends on OpenSSL
==> Fetching OpenSSL
==> Building OpenSSL
Found system OpenSSL library.
==> Testing OpenSSL
**Method 'id' must be implemented by CompUnit::Repository because it is required by a role**  
in any compose_method_table at gen/moar/m-Metamodel.nqp line 2801
  in any apply at gen/moar/m-Metamodel.nqp line 2811
  in any compose at gen/moar/m-Metamodel.nqp line 2984
  in any make_pun at gen/moar/m-Metamodel.nqp line 1683
  in any find_method at gen/moar/m-Metamodel.nqp line 1711
  in method find at C:\rakudo\share\perl6\site\sources\B669D8030E71BA9B7E30E7C0A830FE5471B285EE line 10
  in sub gen-lib at C:\Users\langb\.panda-work\1454665575_1\lib\OpenSSL\NativeLib.pm6 line 22
  in sub guess_library_name at C:\rakudo\share\perl6\sources\075EFE4B4CDAAF73190194EA876F81A1F128D1A2 line 175
  in method setup at C:\rakudo\share\perl6\sources\075EFE4B4CDAAF73190194EA876F81A1F128D1A2 line 225
  in method CALL-ME at C:\rakudo\share\perl6\sources\075EFE4B4CDAAF73190194EA876F81A1F128D1A2 line 241
  in method new at C:\Users\langb\.panda-work\1454665575_1\lib\OpenSSL.pm6 line 28
  in block <unit> at t/01-basic.t line 6

t/01-basic.t ...
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 9/9 subtests

**Comment by ugexe** [comment]
Resolved in 4786ef4
