### ISSUE TITLE
t/01-basic.t test fails on macOS High Sierra

### ISSUE THREAD

**Issue by bbkr** [sergot/openssl#63]
```
===> Testing: OpenSSL:ver<0.1.19>:auth<github:sergot>
# Failed test 'new 3/3'
# at t/01-basic.t line 15
# expected: '65536'
#      got: '771'
# Looks like you failed 1 test of 9
```

```
$ perl6 -v
This is Rakudo version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.
```

```
$ openssl version
LibreSSL 2.2.7
```

MacOS  High Sierra 10.13.5

**Comment by coke** [comment]
Still happening as of ```Rakudo version 2018.09-72-g687a3cbb0 built on MoarVM version 2018.09-123-g0191bd9cf```

**Comment by MattOates** [comment]
Still here, let me know if there is anything I can do to help diagnose this further. Its the main blocker for installing cro on MacOS.

Rakudo version 2018.12-280-gdf96fa0f3 built on MoarVM version 2018.12-45-ga9d02578a
```
$ zef install OpenSSL
===> Searching for: OpenSSL
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Testing: OpenSSL:ver<0.1.21>:auth<github:sergot>
# Failed test 'new 3/3'
# at t/01-basic.t line 15
# expected: '65536'
#      got: '771'
# Looks like you failed 1 test of 9
# NETWORK_TESTING was not set
# NETWORK_TESTING was not set
===> Testing [FAIL]: OpenSSL:ver<0.1.21>:auth<github:sergot>
Aborting due to test failure: OpenSSL:ver<0.1.21>:auth<github:sergot> (use --force-test to override)
```

**Comment by bbkr** [comment]
Still bugged.

**Comment by AngeldsWang** [comment]
FYI. On my mac, the default `ldlibs` in config is `/usr/local/lib`。
```bash
$ perl6 -e 'say $*VM.config<ldlibs>'
 -L/usr/local/lib -lffi -ltommath -latomic_ops -luv -lpthread
```
I didn't find a way to change the configuration and figure out why `LD_LIBRARY_PATH` do not work neither. But after linking `libssl.dylib` from `/usr/local/opt/openssl/lib` into `/usr/local/lib`, the error had gone away.

**Comment by scovit** [comment]
The bug is still there. MacOS mojave

```
$ openssl version
LibreSSL 2.6.5
```

**Comment by scovit** [comment]
https://github.com/sergot/openssl/pull/73 might fix the issue, although, quite frankly, I do not know which kind of functionality that test is testing, why it has been written in the first place, and why it should be one way or the other?

**Comment by Digicrat** [comment]
Same issue here on Mojave after upgrading Rakudo to 2020.01 release.  

I used the "--force-test" option to bypass the test on this module and continue with installing the modules I need.
