### ISSUE TITLE
Latest commits don't work with github.com

### ISSUE THREAD

**Issue by ugexe** [sergot/openssl#7]
Not quite sure why. It worked fine a few days ago but there are too many changes for me to dig through everything. Seems like it may be failing its handshake, having a problem reading all the data it needs to, or is not handling errors correctly at first glance (ERR_get_error shifts off the error stack and should be iterated over every time errors are checked [it doesnt inside method set-socket] [not to be confused with SSL_get_error] so that every time you call it you know there are no old values in the stack)

Here is some debugging output:

    nickl@localhost:~/perl6/openssl$ perl6 -MIO::Socket::SSL -e 'use v6; my $host="github.com"; my $port = 443; my $ssl = IO::Socket::SSL.new(:$host, :$port); $ssl.send("GET / \r\n\r\n"); say $ssl.^methods; say $ssl.recv'

    NEW
    VERSION: unknown
    METHOD: SSL_METHOD<139841533098768>
    SOCKET: IO::Socket::INET.new(encoding => "utf8", host => "github.com", port => 443, localhost => Str, localport => Int, listen => Bool, family => 2, proto => 6, type => 1, input-line-separator => "\n", ins => 0)
    writing...
    reading...
    finished
    SET-CONNECT-STATE
    CONNECT
    HANDLE-ERROR
    ERROR: 2
    BIO-WRITE
             ÐÌ�uÇÁpK»Sª,Ø=�V­|+$ÀC©�ô·K�øAÍ¼ZÀÀ
    98��ÀÀ5�ÀÀ      32��EDÀÀ/�AÀÀÀ
    ÀÀÀ
           ÿI

    42
                                                                                                                                     #
    BIO-READ
    HANDLE-ERROR
    ERROR: 2
    BIO-WRITE
             FBA¢S®Äõç�&5ÊG=$ýÑGÀËæÎ¼Uà´w�aQNÉ      .�Ú}k�Æ
    6Ïæÿ:½Ï@ì_ãÈ�Jtx÷0×u×7�¥�
                             d|:Aÿ öTòÂ�VPhÆ ví8�Fí­eùÕXB   úäP¼Hûé
    BIO-READ
    HANDLE-ERROR
    ERROR: 0
    WRITE (Str)
             val: GET /

    WRITE (Blob)
             val: GET /

    HANDLE-ERROR
    ERROR: 0
    BIO-WRITE
              ,h!YÈ�mÜ[«�>$Ù��C2æS|uªVÏ·Þ®F( úAµ�¥�Ä«feêk¨W3s�[S¸1b�Vò6r�à
    READ
    HANDLE-ERROR
    ERROR: 2
    BIO-WRITE
    BIO-READ
    HTTP/1.1 301 Moved Permanently
    Content-length: 0
    Location: https://github.com/
    Connection: close

**Comment by retupmoca** [comment]
Your debugging information looks fine?

github is responding, and you're getting the response - the response is just a redirect since you didn't pass along a Host: header.

**Comment by retupmoca** [comment]
Note that I did just fix an issue where it would hang and use 100% of cpu if the Perl6 socket closed; was that the behavior you were seeing? If so, try the latest commit.

**Comment by ugexe** [comment]
That was the behavior I had with HTTP::UserAgent using SSL (which is why I overlooked my mistake on the Host header). It does appear to work with your latest changes :+1:
